CREATE OR REPLACE FUNCTION FN_NOME_FUNCIONARIO (F_ID_FUNCIONARIO IN FUNCIONARIO.ID_FUNCIONARIO%TYPE) RETURN FUNCIONARIO.NOME%TYPE IS
    CURSOR cur_funcionario(C_ID_FUNCIONARIO FUNCIONARIO.ID_FUNCIONARIO%TYPE) IS
        SELECT ID_FUNCIONARIO, NOME FROM FUNCIONARIO WHERE ID_FUNCIONARIO = C_ID_FUNCIONARIO;
    V_ID_FUNCIONARIO FUNCIONARIO.ID_FUNCIONARIO%TYPE;
    V_NOME           FUNCIONARIO.NOME%TYPE;
    
    BEGIN
    OPEN cur_funcionario(F_ID_FUNCIONARIO);
        FETCH cur_funcionario INTO V_ID_FUNCIONARIO, V_NOME;
    CLOSE cur_funcionario;
    RETURN V_NOME;
END FN_NOME_FUNCIONARIO;
/
SELECT FN_NOME_FUNCIONARIO(100) FROM DUAL;