CREATE OR REPLACE PROCEDURE SP_CONFERE_NOME_FUNCIONARIO (P_ID_FUNCIONARIO   NUMBER,
                                                         P_NOME_FUNCIONARIO VARCHAR2) IS
    V_NM_FUNCIONARIO funcionario.nome%Type;
BEGIN
    SELECT NOME
    INTO V_NM_FUNCIONARIO
    FROM funcIonario
    WHERE id_funcionario = P_ID_FUNCIONARIO;
    
    IF V_NM_FUNCIONARIO = P_NOME_FUNCIONARIO THEN
        DBMS_OUTPUT.PUT_LINE(V_NM_FUNCIONARIO);
    ELSE
        DBMS_OUTPUT.PUT_LINE('NOK');
    END IF;
END SP_CONFERE_NOME_FUNCIONARIO;
/

BEGIN
    SP_CONFERE_NOME_FUNCIONARIO(P_ID_FUNCIONARIO => 10, P_NOME_FUNCIONARIO => 'Marcos');
END;
/