BEGIN
FOR i IN 1 .. 10 LOOP
    DBMS_OUTPUT.PUT_LINE('A variável i vale ' || i);
END LOOP;
END;
/

DECLARE
V_NUM_INICIAL   NUMBER := &INICIAL;
V_NUM_FINAL     NUMBER := &FINAL;
BEGIN
    FOR i IN V_NUM_INICIAL .. V_NUM_FINAL LOOP
        DBMS_OUTPUT.PUT_LINE(i);
    END LOOP;
END;
/

