SET SERVEROUTPUT ON;
DECLARE
    V_NM_FUNCIONARIO    funcionario.nome%Type;
    V_BOOLEANA           BOOLEAN := FALSE;
    --V_NM_FUNCIONARIO VARCHAR2(2);
BEGIN
    SELECT NOME
    INTO V_NM_FUNCIONARIO
    FROM funcIonario
    WHERE id_funcionario = 10;
    
    IF V_NM_FUNCIONARIO = 'Marcos' AND V_BOOLEANA = TRUE THEN
        DBMS_OUTPUT.PUT_LINE(V_NM_FUNCIONARIO);
    ELSIF V_NM_FUNCIONARIO = 'Marcos' AND V_BOOLEANA = FALSE THEN
        DBMS_OUTPUT.PUT_LINE('Nome é Marcos mas BOOLEANA é FALSE');
    ELSE
        DBMS_OUTPUT.PUT_LINE('NOK');
    END IF;
    EXCEPTION WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
/