CREATE OR REPLACE TRIGGER TGR_FUNCIONARIO 
BEFORE UPDATE OR DELETE ON FUNCIONARIO
FOR EACH ROW
BEGIN
    IF UPDATING THEN
        DBMS_OUTPUT.PUT_LINE('Realizando UPDATE');
        DBMS_OUTPUT.PUT_LINE('Nome Novo:   ' || :NEW.NOME);
    ELSIF DELETING THEN
        DBMS_OUTPUT.PUT_LINE('Realizando DELETE');
    END IF;
    DBMS_OUTPUT.PUT_LINE('Nome Antigo: ' || :OLD.NOME);
END TGR_FUNCIONARIO;

UPDATE FUNCIONARIO SET NOME = 'Marcos Novo' WHERE ID_FUNCIONARIO = 10;

DELETE FROM FUNCIONARIO WHERE ID_FUNCIONARIO = 13;