--DROP TABLE FUNCIONARIO
--Criar Tabela funcionário com os campos ID_FUNCIONARIO, NOME e SALARIO
CREATE TABLE FUNCIONARIO (
    ID_FUNCIONARIO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME           VARCHAR2(100),
    SALARIO        NUMBER(10, 2)
);