DROP TABLE FUNCIONARIO2
--Criar Tabela funcionário com os campos ID_FUNCIONARIO, NOME e SALARIO
CREATE TABLE FUNCIONARIO2 (
    ID_FUNCIONARIO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME           VARCHAR2(100),
    SALARIO        NUMBER(10, 2));
COMMIT;
