BEGIN
INSERT INTO FUNCIONARIO2 (NOME, SALARIO) VALUES (
SELECT NOME, SALARIO FROM FUNCIONARIO WHERE ID_FUNCIONARIO = 13);
COMMIT;
END;
/

SELECT NOME, SALARIO FROM FUNCIONARIO WHERE (ID_FUNCIONARIO < 13);

SELECT * FROM FUNCIONARIO2;

SELECT NOME, SALARIO FROM FUNCIONARIO WHERE ID_FUNCIONARIO < 3;