DECLARE
NOME_FUNCIONARIO    VARCHAR2;
SALARIO_NOVO        NUMBER(10, 2);
BEGIN
SELECT NOME, SALARIO INTO NOME_FUNCIONARIO, SALARIO_NOVO FROM FUNCIONARIO WHERE ID_FUNCIONARIO = 10;
--DBMS_OUTPUT.PUT_LINE(NOME_FUNCIONARIO || SALARIO_NOVO);
SALARIO_NOVO        := SALARIO_NOVO * 1.05;
NOME_FUNCIONARIO    := NOME_FUNCIONARIO || ' INSERT INTO SELECT VARIABLE';
INSERT INTO FUNCIONARIO2 (NOME, SALARIO) VALUES (NOME_FUNCIONARIO, SALARIO_NOVO);
COMMIT;
END;
/

DELETE FROM FUNCIONARIO2 WHERE ID_FUNCIONARIO > 3;

BEGIN
UPDATE  FUNCIONARIO2 SET
            NOME = 'Joana', SALARIO = 1000.10
        WHERE ID_FUNCIONARIO = 3;
COMMIT;
END;
/