CREATE OR REPLACE PACKAGE BODY PKG_CONTROLA_FUNCIONARIO IS
FUNCTION FN_NOME_FUNCIONARIO (F_ID_FUNCIONARIO IN FUNCIONARIO.ID_FUNCIONARIO%TYPE) RETURN FUNCIONARIO.NOME%TYPE IS
    CURSOR cur_funcionario(C_ID_FUNCIONARIO FUNCIONARIO.ID_FUNCIONARIO%TYPE) IS
        SELECT ID_FUNCIONARIO, NOME FROM FUNCIONARIO WHERE ID_FUNCIONARIO = C_ID_FUNCIONARIO;
    V_ID_FUNCIONARIO FUNCIONARIO.ID_FUNCIONARIO%TYPE;
    V_NOME           FUNCIONARIO.NOME%TYPE;
    
    BEGIN
    OPEN cur_funcionario(F_ID_FUNCIONARIO);
        FETCH cur_funcionario INTO V_ID_FUNCIONARIO, V_NOME;
    CLOSE cur_funcionario;
    RETURN V_NOME;
END FN_NOME_FUNCIONARIO;

PROCEDURE SP_REL_FUNCIONARIOS (P_ID_FUNCIONARIO   IN  FUNCIONARIO.ID_FUNCIONARIO%TYPE,
                                                 P_NOME             OUT FUNCIONARIO.NOME%TYPE,
                                                 P_SALARIO          OUT FUNCIONARIO.SALARIO%TYPE)IS
    CURSOR cur_funcionario(C_ID_FUNCIONARIO FUNCIONARIO.ID_FUNCIONARIO%TYPE) IS
        SELECT ID_FUNCIONARIO, NOME, SALARIO FROM FUNCIONARIO WHERE ID_FUNCIONARIO = C_ID_FUNCIONARIO;
    V_ID_FUNCIONARIO FUNCIONARIO.ID_FUNCIONARIO%TYPE;
    V_NOME           FUNCIONARIO.NOME%TYPE;
    V_SALARIO        FUNCIONARIO.SALARIO%TYPE;
    
    BEGIN
    --V_ID_FUNCIONARIO := 10;
    OPEN cur_funcionario(P_ID_FUNCIONARIO);
        FETCH cur_funcionario INTO V_ID_FUNCIONARIO, V_NOME, V_SALARIO;
    CLOSE cur_funcionario;
    P_NOME              := V_NOME;
    P_SALARIO           := V_SALARIO;
END SP_REL_FUNCIONARIOS;
END PKG_CONTROLA_FUNCIONARIO;