CREATE OR REPLACE PACKAGE PKG_CONTROLA_FUNCIONARIO IS
    PROCEDURE SP_REL_FUNCIONARIOS (P_ID_FUNCIONARIO   IN  FUNCIONARIO.ID_FUNCIONARIO%TYPE,
                                                     P_NOME             OUT FUNCIONARIO.NOME%TYPE,
                                                     P_SALARIO          OUT FUNCIONARIO.SALARIO%TYPE);
END PKG_CONTROLA_FUNCIONARIO;